# Generated by Django 3.0.5 on 2020-05-03 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_unit_type', models.CharField(max_length=50)),
                ('address_city', models.CharField(max_length=50)),
                ('address_street', models.CharField(max_length=50)),
                ('address_zip_code', models.CharField(max_length=10)),
                ('address_number', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cexpense_type', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(max_length=50)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comments', models.CharField(max_length=100)),
                ('pdf_file', models.FileField(upload_to='')),
                ('rental_unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.RentalUnit')),
            ],
        ),
    ]
