# Generated by Django 3.0.5 on 2020-05-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalunit',
            name='address_number',
            field=models.CharField(max_length=10),
        ),
    ]
