# Generated by Django 3.0.5 on 2020-05-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20200503_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cexpense_type',
        ),
    ]
