# Generated by Django 3.0.5 on 2020-05-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_remove_transaction_cexpense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='pdf_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
