# Generated by Django 3.0.5 on 2020-05-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20200503_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
