# Generated by Django 3.0.5 on 2020-05-06 16:47

from django.db import migrations
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20200503_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=partial_date.fields.PartialDateField(),
        ),
    ]
