# Generated by Django 3.0.5 on 2020-05-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_auto_20200506_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalunit',
            name='rental_unit_type',
            field=models.CharField(choices=[('A', 'Apartment'), ('G', 'Garage'), ('H', 'House')], max_length=1),
        ),
    ]
