# Generated by Django 3.0.5 on 2020-05-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_auto_20200506_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('R', 'Revenue'), ('I', 'Insurance'), ('P', 'Property Taxes'), ('E', 'Electricity'), ('A', 'Administration fees'), ('O', 'Other')], max_length=1),
        ),
    ]
