# Generated by Django 3.0.5 on 2020-05-20 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_auto_20200511_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalunit',
            options={'ordering': ['-address_city', '-address_street', '-address_number']},
        ),
    ]
