# Generated by Django 3.0.5 on 2020-05-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_auto_20200520_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='comments',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
