# Generated by Django 3.0.5 on 2020-05-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_auto_20200523_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(),
        ),
    ]
