# Generated by Django 3.0.5 on 2020-06-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0013_auto_20200524_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
