# Generated by Django 3.0.5 on 2020-06-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0014_auto_20200606_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='comments',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
