# Generated by Django 3.0.5 on 2020-06-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0015_auto_20200606_1443'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rentalunit',
            unique_together={('rental_unit_type', 'address_city', 'address_street', 'address_zip_code', 'address_number')},
        ),
    ]
