# Generated by Django 3.0.5 on 2020-06-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0016_auto_20200606_1453'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rentalunit',
            unique_together=set(),
        ),
    ]
